In [1]:
import numpy as np

In [2]:
def H(X):
    return -np.sum( [ x*np.log2(x) for x in X if x > 0] )
def get_MI(e1,e2,int_e1_e2, total):
    M_aux = np.zeros( (len(total),len(total)) )
    for i in range(len(e1)):
        for j in range(len(e2)):
            if i!=j:
                M_aux[i,j] = e1[i]/total[i]+e2[j]/total[j]
            else:
                M_aux[i,j] = (e1[i]+e2[i]-int_e1_e2[i])/total[i]
                
    # Marginalization
    M = M_aux/M_aux.sum()
    me1 = M.sum(axis=0) / M.sum()
    me2 = M.sum(axis=1) / M.sum()
    MI = 0
    for i in range(len(e1)):
        for j in range(len(e2)):
            if M[i,j] > 0:
                MI += M[i,j]*np.log2( M[i,j]/(me1[i]*me2[j]) )
    result = (2.*MI)/(H(me1) + H(me2))
    print(e1)
    print(e2)
    print(int_e1_e2)
    print(total)
    print(M)
    print(me1, me2)
    print(H(me1), H(me2))
    return (1.-result, MI, 1.-2.*1./(1.+np.exp(result)))

In [3]:
total     = np.array( [100, 100, 50, 50] ) # Quantidade de documentos de cada classe o termo t ocorre

In [4]:
e1        = np.array( [ 40,  30, 20, 30] ) # Frequencias de cada vertice para cada classe
e2        = np.array( [ 40,  30, 20, 30] )
int_e1_e2 = np.array( [ 20,  15, 10, 15] ) # Quantidade de documentos que os vertices ocorrem em comum
get_MI(e1,e2,int_e1_e2,total)

[40 30 20 30]
[40 30 20 30]
[20 15 10 15]
[100 100  50  50]
[[0.04705882 0.05490196 0.0627451  0.07843137]
 [0.05490196 0.03529412 0.05490196 0.07058824]
 [0.0627451  0.05490196 0.04705882 0.07843137]
 [0.07843137 0.07058824 0.07843137 0.07058824]]
[0.24313725 0.21568627 0.24313725 0.29803922] [0.24313725 0.21568627 0.24313725 0.29803922]
1.9898921907665392 1.9898921907665392


(0.9940968538539797, 0.011746624416919326, 0.002951564501884718)

In [5]:
e1        = np.array( [ 40,  30, 20, 30] ) # Frequencias de cada vertice para cada classe
e2        = np.array( [ 40,  30, 20, 30] )
int_e1_e2 = np.array( [  0,   0,  0,  0] ) # Quantidade de documentos que os vertices ocorrem em comum
get_MI(e1,e2,int_e1_e2,total)

[40 30 20 30]
[40 30 20 30]
[0 0 0 0]
[100 100  50  50]
[[0.05882353 0.05147059 0.05882353 0.07352941]
 [0.05147059 0.04411765 0.05147059 0.06617647]
 [0.05882353 0.05147059 0.05882353 0.07352941]
 [0.07352941 0.06617647 0.07352941 0.08823529]]
[0.24264706 0.21323529 0.24264706 0.30147059] [0.24264706 0.21323529 0.24264706 0.30147059]
1.988410687384906 1.988410687384906


(0.9999120003269258, 0.00017497949042710346, 4.39998365086014e-05)

In [6]:
e1        = np.array( [  0,  30,  0, 10] ) # Frequencias de cada vertice para cada classe
e2        = np.array( [ 40,   0, 20,  0] )
int_e1_e2 = np.array( [  0,   0,  0,  0] ) # Quantidade de documentos que os vertices ocorrem em comum
get_MI(e1,e2,int_e1_e2,total)

[ 0 30  0 10]
[40  0 20  0]
[0 0 0 0]
[100 100  50  50]
[[0.07692308 0.         0.07692308 0.        ]
 [0.13461538 0.05769231 0.13461538 0.05769231]
 [0.07692308 0.         0.07692308 0.        ]
 [0.11538462 0.03846154 0.11538462 0.03846154]]
[0.40384615 0.09615385 0.40384615 0.09615385] [0.15384615 0.38461538 0.15384615 0.30769231]
1.7062740891876007 1.884313527799799


(0.027596184012652736, 1.7457505501977317, 0.45119673986979514)

In [11]:
e1        = np.array( [ 75, 80, 35, 37] ) # Frequencias de cada vertice para cada classe
e2        = np.array( [ 75, 80, 35, 37] )
int_e1_e2 = np.array( [ 25, 60, 10, 24] ) # Quantidade de documentos que os vertices ocorrem em comum
get_MI(e1,e2,int_e1_e2,total)

[75 80 35 37]
[75 80 35 37]
[25 60 10 24]
[100 100  50  50]
[[0.05582849 0.06922733 0.06476105 0.06654757]
 [0.06922733 0.0446628  0.06699419 0.06878071]
 [0.06476105 0.06699419 0.05359536 0.06431443]
 [0.06654757 0.06878071 0.06431443 0.0446628 ]]
[0.25636445 0.24966503 0.24966503 0.24430549] [0.25636445 0.24966503 0.24966503 0.24430549]
1.9997891710401547 1.9997891710401547


(0.9939266858484312, 0.012145347872632013, 0.0030366477418574123)

In [15]:
e1        = np.array( [ 100,   0, 50,  0] ) # Frequencias de cada vertice para cada classe
e2        = np.array( [   0, 100,  0, 50] )
int_e1_e2 = np.array( [   0,   0,  0,  0] ) # Quantidade de documentos que os vertices ocorrem em comum
get_MI(e1,e2,int_e1_e2,total)

[100   0  50   0]
[  0 100   0  50]
[0 0 0 0]
[100 100  50  50]
[[0.0625 0.125  0.0625 0.125 ]
 [0.     0.0625 0.     0.0625]
 [0.0625 0.125  0.0625 0.125 ]
 [0.     0.0625 0.     0.0625]]
[0.125 0.375 0.125 0.375] [0.375 0.125 0.375 0.125]
1.811278124459133 1.811278124459133


(0.05728516974757525, 1.7075187496394217, 0.43929542829152723)

In [22]:
M_aux = np.zeros( (4,4) )
for i in range(len(e1)):
    for j in range(len(e2)):
        if i!=j:
            M_aux[i,j] = e1[i]/total[i]+e2[j]/total[j]
        else:
            M_aux[i,j] = (e1[i]+e2[i]-int_e1_e2[i])/total[i]
M = M_aux/M_aux.sum()

In [23]:
# Marginalization
me1 = M.sum(axis=0) / M.sum()
me2 = M.sum(axis=1) / M.sum()

In [24]:
MI = 0
for i in range(len(e1)):
    for j in range(len(e2)):
        if M[i,j] > 0:
            MI += M[i,j]*np.log2( M[i,j]/(me1[i]*me2[j]) )
result = (2.*MI)/(H(me1) + H(me2))
result, MI, 1./(1.+np.exp(np.log2(1.+result)))

(0.1771397536008214, 0.3460237627052308, 0.44144846262351356)

In [12]:
def simulate(total):
    e1        = np.array(list(map(np.random.choice, list(map(range, total)))))
    e2        = np.array(list(map(np.random.choice, list(map(range, total)))))
    
    int_e1_e2 = np.zeros(len(total), dtype=int)
    me = list(map(min, zip(e1,e2)))
    
    for i in range(len(total)):
        if me[i] > 0:
            int_e1_e2[i] = np.random.choice(range(me[i]))
    total = list(map(max, zip(total,e1+e2-int_e1_e2)))
    
    return get_MI(e1,e2,int_e1_e2, total)

In [14]:
for i in range(20):
    print(simulate(np.array([10,20,30,40,50])))

[ 3 19 25 14 26]
[ 7 10  2 18 37]
[ 0  2  1 11 24]
[10, 27, 30, 40, 50]
[[0.04113878 0.02757822 0.01508422 0.03085409 0.04278433]
 [0.05774666 0.04113878 0.0316921  0.04746197 0.05939221]
 [0.06307947 0.0495189  0.03565361 0.05279477 0.06472502]
 [0.04319572 0.02963516 0.01714116 0.02159786 0.04484127]
 [0.05018931 0.03662875 0.02413475 0.03990462 0.03208825]]
[0.25534995 0.18449982 0.12370584 0.1926133  0.24383109] [0.15743964 0.23743172 0.26577177 0.15641117 0.18294569]
2.279885008857561 2.2874889358769863
(0.8733238870730446, 0.2892885888014136, 0.06325349419782178)
[ 0 19 23 12 10]
[ 8 11 15 13  2]
[0 1 1 0 0]
[10, 29, 37, 40, 50]
[[0.04307783 0.02042483 0.02182998 0.01750037 0.00215389]
 [0.07835708 0.05384728 0.05710923 0.05277962 0.03743315]
 [0.07655046 0.05389747 0.05384728 0.050973   0.03562653]
 [0.05923201 0.03657902 0.03798416 0.03365455 0.01830808]
 [0.05384728 0.03119429 0.03259944 0.02826982 0.01292335]]
[0.31106466 0.19594289 0.2033701  0.18317737 0.10644499] [0.104986

In [116]:
get_MI([9, 0], [0, 10], [0, 0], [10, 20])

[9, 0]
[0, 10]
[0, 0]
[10, 20]
[[0.32142857 0.5       ]
 [0.         0.17857143]]
[0.32142857 0.67857143] [0.82142857 0.17857143]
0.9059282160429991 0.676941869780886


(-1.2143893030385122, 1.7525452930740315, 0.8030685072536887)

In [57]:
np.array(list(map(np.random.choice, list(map(range, total))))), total

(array([ 4, 34, 27, 37]), array([100, 100,  50,  50]))

[8, 23, 17, 13]